name: Boardbyte CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  DIR: '/var/www/html/boardbyte-api'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ${{ env.DIR }}
            git pull origin main
            yarn && yarn build
            pm2 delete boardbyte >> /dev/null && pm2 start dist/index.js --name boardbyte
